### ISSUE TITLE
1주차 과제 추가 코멘트

### ISSUE THREAD

**Issue by sunsidew** [bina0229/sparta#1]
https://github.com/bina0229/sparta/blob/28f3c1c7c974522868666171593baf0e31625f57/0110_homework_%EC%87%BC%ED%95%91%EB%AA%B0.html#L26

여백이나 margin: auto 잘 주셨습니다! width는 특정 픽셀만큼 줄수도 있지만 쓰신 것처럼 비율로 줄 수도 있어요! 물론 parent의 수치의 비율입니다 ㅎㅎ

https://github.com/bina0229/sparta/blob/28f3c1c7c974522868666171593baf0e31625f57/0110_homework_%EC%87%BC%ED%95%91%EB%AA%B0.html#L31

btn btn-primary는 bootstrap에서 정의한 클래스죠! 해당 클래스에 추가 스타일을 주는게 불가능하지는 않습니다만, 해당 클래스를 사용하는 다른 html 태그가 의도랑 다르게 동작할 가능성도 있기 때문에 내가 주고싶은 태그에 별도 클래스나 id를 줘서 스타일을 주시는게 좋습니다. 해당 클래스를 `.order_btn {text-align: center;}` 과 같은 임의의 이름 (order_btn)으로 바꿔주고 

https://github.com/bina0229/sparta/blob/28f3c1c7c974522868666171593baf0e31625f57/0110_homework_%EC%87%BC%ED%95%91%EB%AA%B0.html#L83
을 `<button type="button" class="order_btn btn btn-primary">주문하기</button>`

처럼 바꿔주시는 방법처럼요 :)

**Comment by bina0229** [comment]
코멘트대로 바꾸어 본것 같은데.. 주문하기 버튼이 여전히 가운데로 안가네요.. 흠..
여백이랑 정렬하는게 은근 까다로운 것 같아요.

**Comment by bina0229** [comment]
3주차과제하면서 가운데정렬 적용했습니다~~
